[workspace]
members = [
    "bindings/rust/evmc-sys",
    "bindings/rust/evmc-vm",
    "bindings/rust/evmc-declare",
    "bindings/rust/evmc-declare-tests",
    "bindings/rust/evmc-loader",
    "examples/example-rust-vm"
]
