version: 2.1

commands:
  build:
    parameters:
      build_type:
        type: string
        default: ""
      toolchain:
        type: string
        default: ""
    steps:
      - run:
          name: "Environment"
          command: |
            CC=${CC:-cc}
            CXX=${CXX:-cpp}
            echo CC: $CC
            echo CXX: $CXX
            $CC --version
            $CXX --version
            cmake --version

            # Create the toolchain.info file for cache key.
            echo '<<parameters.toolchain>>' >> toolchain.info
            echo '<<parameters.build_type>>' >> toolchain.info
            $CXX --version >> toolchain.info
      - restore_cache:
          name: "Restore Hunter Cache"
          key: &hunter-cache-key hunter-{{arch}}-{{checksum "toolchain.info"}}-{{checksum "cmake/Hunter/init.cmake"}}
      - run:
          name: "Configure"
          working_directory: ~/build
          command: |
            cmake ../project <<#parameters.build_type>>-DCMAKE_BUILD_TYPE=<<parameters.build_type>><</parameters.build_type>> <<#parameters.toolchain>>-DCMAKE_TOOLCHAIN_FILE=~/project/cmake/cable/toolchains/<<parameters.toolchain>>.cmake<</parameters.toolchain>> -DCMAKE_INSTALL_PREFIX=~/install -DEVMC_TESTING=ON $CMAKE_OPTIONS
      - save_cache:
          name: "Save Hunter Cache"
          key: *hunter-cache-key
          paths:
            - ~/.hunter/_Base/Cache
      - run:
          name: "Build"
          command: cmake --build ~/build -- -j4
      - run:
          name: "Install"
          command: cmake --build ~/build --target install
      - run:
          name: "Package"
          command: |
            cmake --build ~/build --target package_source
            cmake --build ~/build --target package
            mkdir ~/package
            mv ~/build/evmc-*.tar.gz ~/package
      - store_artifacts:
          path: ~/package
          destination: package
      - persist_to_workspace:
          root: ~/build
          paths:
            - bin/evmc-vmtester
            - examples/evmc-example

  test:
    steps:
      - run:
          name: "Test"
          command: |
            cmake --build ~/build --target test -- ARGS="-j4 --schedule-random --output-on-failure"
            # Test statically linked end-to-end example
            ~/build/examples/evmc-example-static
            # Test dynamically loaded end-to-end example
            ~/build/examples/evmc-example ~/build/examples/example_vm/libexample-vm.so

jobs:

  lint:
    docker:
      - image: ethereum/cpp-build-env:12-lint
    steps:
    - checkout
    - run:
        name: "Check code format"
        command: |
          clang-format --version
          find bindings examples include lib test tools -name '*.hpp' -o -name '*.cpp' -o -name '*.h' -o -name '*.c' | xargs clang-format -i
          git diff --color --exit-code
    - run:
        name: "Run codespell"
        command: |
          codespell --quiet-level=4 --ignore-words=./.codespell-whitelist --skip=.git
    - run:
        name: "Check bumpversion"
        command: |
          export PATH="/home/builder/.local/bin:$PATH"
          pip3 install bumpversion
          bumpversion --dry-run --verbose major
          bumpversion --dry-run --verbose minor
          bumpversion --dry-run --verbose patch
    - run:
        name: "Test documentation"
        command: |
          cat Doxyfile | sed 's/HTML_OUTPUT            = ./HTML_OUTPUT            = ..\/docs/' | doxygen - > doxygen.log 2> doxygen.warnings
          if [ -s doxygen.warnings ]; then
            printf '\n\nDoxygen warnings:\n\n'
            cat doxygen.warnings
            exit 1
          fi
          cat doxygen.log
    - store_artifacts:
        path: ~/docs
        destination: docs

  upload-docs:
    docker:
      - image: ethereum/cpp-build-env:12-lint
    steps:
      - checkout
      - run:
          name: "Generate documentation"
          command: doxygen Doxyfile
      - run:
          name: "Upload documentation"
          command: |
            git config user.email "docs-bot@ethereum.org"
            git config user.name "Documentation Bot"
            git add --all
            git commit -m "Update docs"
            git push -f "https://$GITHUB_TOKEN@github.com/ethereum/evmc.git" HEAD:gh-pages

  build-clang10-coverage:
    docker:
      - image: ethereum/cpp-build-env:14-clang-10
    steps:
      - checkout
      - build:
          build_type: Coverage
      - test
      - run:
          name: "Collect coverage data"
          working_directory: ~/build
          command: |
            find -name '*.profraw'
            llvm-profdata merge *.profraw -o evmc.profdata
            llvm-cov report -instr-profile evmc.profdata \
              -object test/evmc-unittests \
              -object bin/evmc-vmtester
            llvm-cov export -instr-profile evmc.profdata -format=lcov > evmc.lcov \
              -object test/evmc-unittests \
              -object bin/evmc \
              -object bin/evmc-vmtester
            genhtml evmc.lcov -o coverage -t EVMC
      - store_artifacts:
          path: ~/build/coverage
          destination: coverage
      - run:
          name: "Upload to Codecov"
          command: |
            # Convert to relative paths
            sed -i 's|$(pwd)/||' ~/build/evmc.lcov
            codecov --file ~/build/evmc.lcov -X gcov


  build-gcc8-cxx17:
    docker:
      - image: ethereum/cpp-build-env:12-gcc-8
    environment:
      CMAKE_OPTIONS: -DCMAKE_CXX_STANDARD=17
    steps:
      - checkout
      - build
      - test

  build-gcc10-cxx17-sanitizers:
    docker:
      - image: ethereum/cpp-build-env:14-gcc-10
    environment:
      CMAKE_OPTIONS: -DCMAKE_CXX_STANDARD=17 -DSANITIZE=address,undefined
    steps:
      - checkout
      - build
      - test

  build-clang10-cxx17-sanitizers:
    docker:
      - image: ethereum/cpp-build-env:14-clang-10
    environment:
      CMAKE_OPTIONS: -DCMAKE_CXX_STANDARD=17 -DSANITIZE=address,undefined,nullability,implicit-unsigned-integer-truncation,implicit-signed-integer-truncation
      UBSAN_OPTIONS: halt_on_error=1
    steps:
      - checkout
      - build
      - test

  build-clang9-cxx14-asan:
    docker:
      - image: ethereum/cpp-build-env:12-clang-9
    environment:
      CMAKE_OPTIONS: -DCMAKE_CXX_STANDARD=14 -DSANITIZE=address
      UBSAN_OPTIONS: halt_on_error=1
    steps:
      - checkout
      - build
      - test

  build-gcc6:
    docker:
      - image: ethereum/cpp-build-env:12-gcc-6
    steps:
      - checkout
      - build
      - test

  build-clang5:
    docker:
      - image: ethereum/cpp-build-env:12-clang-5
    steps:
      - checkout
      - build
      - test

  build-clang38:
    docker:
      - image: ethereum/cpp-build-env:12-clang-3.8
    steps:
      - checkout
      - build
      - test

  build-gcc-32bit:
    docker:
      - image: ethereum/cpp-build-env:14-gcc-10-multilib
    steps:
      - checkout
      - build:
          toolchain: cxx11-32bit
      - test

  build-cmake-min:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - run:
          name: "Install default CMake"
          command: sudo apt -q update && sudo apt -qy install cmake
      - checkout
      - build
      - test

  bindings-go-latest:
    docker:
      - image: circleci/golang
    steps: &bindings-go-steps
      - checkout
      - run:
          name: "Environment"
          command: |
            go version
            go env
            gcc --version
      - run:
          name: "Go Build"
          command: |
            go build -v ./bindings/go/evmc
            go vet -v ./bindings/go/evmc
            go generate -v ./bindings/go/evmc
            go test -v ./bindings/go/evmc
      - run:
          name: "Go module integration test"
          working_directory: test/gomod
          command: |
            V=$CIRCLE_TAG
            if [ -z $V ]; then
              V=$CIRCLE_SHA1
            fi
            echo "version: $V"

            go mod init evmc.ethereum.org/evmc_use
            go get -v $(grep -o 'github.com/ethereum/evmc/v.*' ../../go.mod)@$V
            go mod tidy -v
            go mod graph
            gcc -shared -I../../include ../../examples/example_vm/example_vm.c -o example-vm.so
            go test -v
            go mod graph


  bindings-go-min:
    docker:
      - image: circleci/golang:1.11
    steps: *bindings-go-steps

  bindings-java:
    docker:
      - image: circleci/openjdk:13-buster
    environment:
      CMAKE_OPTIONS: -DEVMC_JAVA=ON
    steps:
      - run:
          name: "Install CMake"
          command: |
            sudo apt -qq update
            sudo apt -yq install cmake
      - checkout
      - build
      - test
      - run:
          name: "Java Build"
          command: |
            cd bindings/java && make clean build
      - run:
          name: "Java Test"
          command: |
            cd bindings/java && make test

  bindings-rust:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update environment
          command: |
            apt update
            apt -y install libclang-dev clang
            rustup component add rustfmt
            rustup update
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt --all -- --check
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - attach_workspace:
          at: ~/build
      - run:
          name: Test with evmc-vmtester
          command: |
            ~/build/bin/evmc-vmtester target/debug/libexamplerustvm.so
      - run:
          name: Test with evmc-example
          command: |
            ~/build/examples/evmc-example target/debug/libexamplerustvm.so

  bindings-rust-asan-combined:
    docker:
      - image: rust:1-buster
    steps:
      - checkout
      - run:
          name: Update environment
          command: |
            echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list
            apt -qq update
            apt -yq  install llvm-8-dev clang-8 --no-install-recommends
            rustup toolchain install nightly-x86_64-unknown-linux-gnu
            rustup update
      - run:
          name: Build
          command: RUSTFLAGS="-Z sanitizer=address" ASAN_OPTIONS=detect_leaks=1 cargo +nightly build --target x86_64-unknown-linux-gnu
      - run:
          name: Test
          command: RUSTFLAGS="-Z sanitizer=address -C opt-level=0" ASAN_OPTIONS=detect_leaks=1 cargo +nightly test --target x86_64-unknown-linux-gnu
      - attach_workspace:
          at: ~/build
      - run:
          name: Test with evmc-vmtester
          command: |
            ~/build/bin/evmc-vmtester target/x86_64-unknown-linux-gnu/debug/libexamplerustvm.so
      - run:
          name: Test with evmc-example
          command: |
            ~/build/examples/evmc-example target/x86_64-unknown-linux-gnu/debug/libexamplerustvm.so

workflows:
  version: 2
  evmc:
    jobs:
      - lint
      - build-clang10-coverage
      - build-gcc8-cxx17
      - build-gcc10-cxx17-sanitizers
      - build-clang10-cxx17-sanitizers
      - build-clang9-cxx14-asan
      - build-gcc6
      - build-clang5
      - build-clang38
      - build-gcc-32bit
      - build-cmake-min
      - bindings-go-latest:
          filters:
            tags:
              only: /.*/
      - bindings-go-min:
          filters:
            tags:
              only: /.*/
      - bindings-java
      - bindings-rust:
          requires:
            - build-gcc8-cxx17
      - bindings-rust-asan-combined:
          requires:
            - build-clang9-cxx14-asan
      - upload-docs:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
